name = "infinite-master"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "KV"
id = "94ea3ecf094c429b872d19b7a0389afb"
preview_id = "ID_OF_PREVIEW_KV_NAMESPACE_FOR_LOCAL_DEVELOPMENT"
